version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    # These need to be specifically mentioned, otherwise circle ci throws an error
    environment:
      SECRET_KEY: somesecretkey
      EMAIL_HOST_USER: someuser@gmail.com
      EMAIL_HOST_PASSWORD: sometestpassword
    executor: python/default
    steps:
      - checkout
      - run:
          command: source ../etavenv/bin/activate
          name: Activating virtual env
      # - run: chmod +x manage.py
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
